### ISSUE TITLE
Need help with opening bundled extension pages

### ISSUE THREAD

**Issue by gkrishnaks** [stoically/webextensions-jsdom#3]
Hi. Thanks you for this package and the geckodriver one - I got the geckodriver one to run in GitLab CICD runner using xvfb..

Would like to know if it's possible to open a page bundled within an extension and test it either with jsdom or using geckodriver... if we get the randomly generated ID within the script , then we can load it in new tab as moz-extension:<ID>/page.html and proceed to test it, for example "setting pages" that we can bundle with extension. I am not sure how to get the ID as it's random each time we run the test. What are your thoughts on this and please let me know if there's a way for this.

**Comment by stoically** [comment]
Hi, glad it works for you.

To open a bundled `html` file with webextensions-jsdom you could use the [`fromFile`](https://github.com/webexts/webextensions-jsdom#exported-function-fromfilepath-options) function that is exported from the package.

How to open it with geckodriver is indeed a good question. I've checked the [`addon` property](https://github.com/webexts/webextensions-geckodriver/blob/38476058969549e579a97d4d732516dda0c7f0d7/src/geckodriver.js#L61) returned from the [AddonManager](https://github.com/mozilla/gecko-dev/blob/master/toolkit/mozapps/extensions/AddonManager.jsm) and it doesn't contain the `Internal UUID`, so this would need to be reported on the Firefox Bugzilla.

The only other workaround that comes to mind is programmatically navigating to `about:debugging` and using an appropriate html selector to get the `Internal UUID` from there.

**Comment by gkrishnaks** [comment]
Thanks, I'll look into that. I will create a ticket in Mozilla bug tracker.

**Comment by gkrishnaks** [comment]
I have posted this as an issue in Mozilla bugzilla. Thanks for providing the detailed analysis. https://bugzilla.mozilla.org/show_bug.cgi?id=1534005 
Closing ticket as it's not an issue with webextensions-jsdom

**Comment by stoically** [comment]
@gkrishnaks I've added an additional `internalUUID` function to webextensions-geckodriver based on the response in the Bugzilla ticket.

**Comment by gkrishnaks** [comment]
Thanks!
